environments:
  dev_cdk: "gc_memgraph_secret_name_dev_cdk"
  dev2_cdk: "gc_memgraph_secret_name_dev2_cdk"
model_repo_url: "https://github.com/CBIIT/cds-model.git"
monorepo_url: "https://github.com/CBIIT/general-commons.git"